const { gql } = require('apollo-server-express');

const typeDefs = gql`
type Game {
  id: ID!
  title: String!
  genre: String!
  releaseDate: String!
}

type Subscription {
  newGameLaunched: Game
  newSubscriptionNotification: Notification
}

type Notification {
  id: ID!
  userId: ID!
  content: String!
  seen: Boolean!
}

type SubscriptionType {
  id: ID!
  name: String!
  description: String
  associatedGames: [Game]
}

type Query {
  getUser(userId: ID!): User!
  getGames: [Game!]
  getNotifications(userId: ID!): [Notification!]
  getSubscriptionTypes: [SubscriptionType!]
}

type Mutation {
  signup(email: String!, password: String!): String
  login(email: String!, password: String!): String
  launchGame(title: String!, genre: String!, releaseDate: String!, subscriptionTypeIds: [ID!]!): Game
  createSubscriptionType(name: String!, description: String, associatedGames: [ID!]): SubscriptionType
  subscribeToNotifications(userId: ID!, subscriptionTypeId: ID!): Boolean
  markNotificationAsSeen(notificationId: ID!): Boolean
}

type User {
  id: ID!
  email: String!
  password: String!
  subscriptions: [String!]
}
`;

module.exports = { typeDefs };
