const { gql } = require('apollo-server-express');

const typeDefs = gql`
  type User {
    id: ID!
    email: String!
    password: String!
  }

  type Query {
    getUser(userId: ID!): User!
  }

  type Mutation {
    signup(email: String!, password: String!): String
    login(email: String!, password: String!): String
  }
`;

module.exports = { typeDefs };
